### ISSUE TITLE
 Nightly test failure with @pki/master copr repo

### ISSUE THREAD

**Issue by amore17** [dogtagpki/pki#4710] opened 2024-04-02 06:52 UTC
FreeIPA nightly tests is failing with the copr repo @pki/master. The test is installing IPA server 

See PR #https://github.com/freeipa-pr-ci2/freeipa/pull/3540, with the following [report](http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/c570a07c-f06c-11ee-b706-fa163e8e2127/report.html?sort=result) and [logs](http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/c570a07c-f06c-11ee-b706-fa163e8e2127/test_integration-test_dns_locations.py-TestDNSLocations-install/master.ipa.test/var/log/pki/pki-tomcat/ca/debug.2024-04-01.log.gz):

```
E           subprocess.CalledProcessError: Command '['ipa-server-install', '-n', 'ipa.test', '-r', 'IPA.TEST', '-p', 'Secret.123', '-a', 'Secret.123', '--domain-level=1', '--dirsrv-config-file', '/ipatests/ipatests_dse.ldif', '-U', '--setup-dns', '--forwarder', '192.168.121.1', '--auto-reverse']' returned non-zero exit status 1.

pytest_ipa/integration/host.py:202: CalledProcessError

---------------------------- Captured stderr setup -----------------------------
ipa: ERROR: stderr: Checking DNS domain ipa.test., please wait ...
Reverse record for IP address 192.168.121.144 already exists
Synchronizing time
No SRV records of NTP servers found and no NTP server or pool address was provided.
Attempting to sync time with chronyc.
Process chronyc waitsync failed to sync time!
Unable to sync time with chrony server, assuming the time is in sync. Please check that 123 UDP port is opened, and any time server is on network.
Validate installation settings ...
Create file system structures ...
Perform SELinux labeling ...
Create database backend: dc=ipa,dc=test ...
Perform post-installation tasks ...
Certificate issuance failed (CA_REJECTED: Server at "https://master.ipa.test:8443/ca/agent/ca//profileProcess" replied: 1: Server Internal Error)
The ipa-server-install command failed. See /var/log/ipaserver-install.log for more information

```

**Comment by flo-renaud** [comment] 2024-04-08 07:11
@edewata could you have a look at this regression in the nightly builds?

**Comment by edewata** [comment] 2024-04-08 17:57
@rcritten @tbordaz I think this is the issue I mentioned to you a few days ago. In upstream PKI CI we're only observing this issue in IPA tests which use sequential serial numbers (instead of RSNv3) which still depends on VLV. Was there any VLV-related change in DS recently that might have caused this?

@amore17 @flo-renaud Is it possible to test IPA with RSNv3 enabled by default to isolate the issue?

@fmarco76 We might need to prioritize VLV removal in this area.

**Comment by tbordaz** [comment] 2024-04-09 08:47
@edewata , if I am correct the test ran 389-Directory/2.4.5 that is using VLV/BDB. I know that during the transition VLV/LMDB, @progier discovered VLV bug(s) that have been fixed only in 3.0.

**Comment by edewata** [comment] 2024-04-09 19:00
@tbordaz Thanks for the info.
@amore17 @flo-renaud @rcritten Which DS version was used in the above test? Is it possible to test with the latest DS?

**Comment by flo-renaud** [comment] 2024-04-10 07:58
@edewata you can get the list of packages from the report url: http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/c570a07c-f06c-11ee-b706-fa163e8e2127/installed_packages/installed_packages_master.log.gz
the test is using 389-ds-base-2.4.5-1.fc39.x86_64

**Comment by edewata** [comment] 2024-04-10 16:15
@flo-renaud Thanks. In that case I would suggest switching to DS 3.0 as @tbordaz suggested.

From PKI side it might be possible to change the sequential serial numbers to use paged results instead of VLV, but the performance might downgrade significantly. @fmarco76 might have better idea about this.

**Comment by fmarco76** [comment] 2024-04-11 08:52
@flo-renaud @edewata if update DS is possible and it resolves the problem I think it will be faster.

**Comment by edewata** [comment] 2024-04-18 00:01
Just FYI, I checked PKI CI execution history, here's the last commit where IPA installation was still successful (although there was a subsequent test failure):
https://github.com/dogtagpki/pki/commit/043ab92c59e392fd6ce3fdb06a0898eb255138f6
https://github.com/dogtagpki/pki/actions/runs/8605380653/job/23581813228#step:6:268

Then here is the next commit where IPA installation failure was first observed:
https://github.com/dogtagpki/pki/commit/a54130a86d0780681b17868f6bd2584e46e4a42d
https://github.com/dogtagpki/pki/actions/runs/8607022021/job/23586823996#step:6:149

As you can see, the changes in PKI do not seem to be related at all to IPA, KRA, pkispawn, VLV, simple paged results, or sequential serial numbers. So I'm still thinking that the issue was caused by changes in another package that was pushed to Fedora 39 around the beginning of April.

**Comment by edewata** [comment] 2024-05-13 20:53
FYI, recently @fmarco76 managed to drop VLV dependency from the code that we use to access the cert records in DS:
https://github.com/dogtagpki/pki/pull/4735

With this change at least IPA installation was able to complete successfully:
https://github.com/dogtagpki/pki/actions/runs/9067072889/job/24918746702

There are still some occasional test failures, but they happen after installation so they seem to be unrelated and will be investigated separately.

@amore17 @flo-renaud Please verify IPA installation with the latest PKI COPR build. Thanks!

**Comment by flo-renaud** [comment] 2024-05-14 16:41
@edewata on our last run (with dogtag-pki-base-11.6.0-0.1.alpha1.20240510195204UTC.078a33ca.fc39.noarch) we now see 19 failing tests ([link](https://github.com/freeipa-pr-ci2/freeipa/pull/3662)) instead of 54 the previous week. There is definitely an improvement but we still see some installation issues.
- installation with an externally signed CA cert (looks like pkispawn is expecting a filename but is provided with the cert content instead)
- installation with a self signed CA (issuance of the RA cert fails with Error 56 connecting to https://master.ipa.test:8443/ca/agent/ca//profileReview: Failure when receiving data from the peer). Seems to happen in a scenario install / uninstall / install

**Comment by edewata** [comment] 2024-05-14 17:08
Could we close this ticket and create new tickets for those issues? We will need more specific steps to reproduce and logs too.

**Comment by flo-renaud** [comment] 2024-05-15 09:21
For the externally signed CA I opened this ticket: https://github.com/dogtagpki/pki/issues/4745
I am still trying to reproduce the other issue with Error 56, will create a ticket when I have a reproducer.

In the meantime I agree, we can close this ticket as the problem described here does not happen any more.

**Closed by flo-renaud** 2024-05-15 09:21 UTC

**Comment by flo-renaud** [comment] 2024-05-15 13:57
For the install / uninstall / re-install scneario: ticket https://github.com/dogtagpki/pki/issues/4746
