### ISSUE TITLE
dogtag with podman, systemd service inactive (dead) on restart

### ISSUE THREAD

**Issue by AllanElleuch** [dogtagpki/pki#4696] opened 2024-03-15 14:13 UTC
Hi,

I'm using podman to run dogtagpki. However, I'm having an issue the systemd inside the container is not starting the pki-tomcatd@pki-tomcat.service on restart.

After reading the log of pkispawn command I notice that some service are created

**\<pkispawn logs>**
```
2024-03-15 11:49:17 INFO: Creating /etc/sysconfig/pki/tomcat/pki-tomcat
2024-03-15 11:49:17 INFO: Creating /etc/sysconfig/pki/tomcat/pki-tomcat/pki-tomcat
2024-03-15 11:49:17 INFO: Creating /etc/systemd/system/pki-tomcatd.target.wants/pki-tomcatd@pki-tomcat.service
```

**File: \</etc/systemd/system/pki-tomcatd.target.wants/pki-tomcatd@pki-tomcat.service>**
```

[Unit]
Description=PKI Tomcat Server %i
PartOf=pki-tomcatd.target

[Service]
Type=simple
EnvironmentFile=/usr/share/pki/etc/tomcat.conf
EnvironmentFile=/etc/tomcat/tomcat.conf
Environment="NAME=%i"
EnvironmentFile=-/etc/sysconfig/%i
EnvironmentFile=/usr/share/pki/etc/pki.conf
EnvironmentFile=/etc/pki/pki.conf

ExecStartPre=/usr/sbin/pki-server upgrade %i
ExecStartPre=/usr/sbin/pki-server migrate %i
ExecStartPre=/usr/bin/pkidaemon start %i
ExecStart=/usr/libexec/tomcat/server start
ExecStop=/usr/libexec/tomcat/server stop

SuccessExitStatus=143
User=pkiuser
Group=pkiuser

[Install]
WantedBy=pki-tomcatd.target
```

It is not clear to me how the service are intended to be used by the container.

For you information, I changed the default command of the containers to `/usr/sbin/init` so the container is able to run in systemd mode. However, it is not clear to me why all my services inside the containers are loaded but inactive (dead)

```
systemctl status enable pki-tomcatd@pki-tomcat.service
Unit enable.service could not be found.
○ pki-tomcatd@pki-tomcat.service - PKI Tomcat Server pki-tomcat
     Loaded: loaded (/usr/lib/systemd/system/pki-tomcatd@.service; enabled; preset: disabled)
    Drop-In: /usr/lib/systemd/system/service.d
             └─10-timeout-abort.conf
     Active: inactive (dead)

```

If I run `systemctl  start pki-tomcatd@pki-tomcat.service`, the service start to run as expected.

If you have any hint that would be welcom.

Allan

**Comment by edewata** [comment] 2024-03-20 18:51
Hi, if you're using the `pki-ca` or the `pki-acme` containers that we have, the Tomcat server will run in the foreground instead of in the background, so it will not use systemd. In general it's not recommended to use systemd in containers. We have some tests using these containers:
https://github.com/dogtagpki/pki/blob/master/.github/workflows/ca-container-test.yml
https://github.com/dogtagpki/pki/blob/master/.github/workflows/acme-container-test.yml

If you want to use systemd you might be able to use the `pki-runner` container which is basically just a Fedora container with PKI packages installed, so you will need to run `pkispawn` yourself. Most of other tests that we have are using this container.

Please also note that these containers are still experimental and mainly used for testing. It's not yet ready for production.

**Comment by edewata** [comment] 2024-05-13 19:52
I'm closing this issue since by design we do not use systemd in the CA and ACME containers that we have.

**Closed by edewata** 2024-05-13 19:52 UTC
