### ISSUE TITLE
FreeIPA nightly test failure in CA install with a custom CA subject

### ISSUE THREAD

**Issue by flo-renaud** [dogtagpki/pki#3367] opened 2020-11-02 09:06 UTC
FreeIPA nightly test are failing when setting up the CA with a custom CA subject (with the copr repo pki/master). See the PR #[511](https://github.com/freeipa-pr-ci2/freeipa/pull/511) with the following [report](http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/c71a4764-1c82-11eb-9c95-fa163ef949a7/report.html) and [logs](http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/c71a4764-1c82-11eb-9c95-fa163ef949a7/test_integration-test_ca_custom_sdn.py-TestCACustomSubjectDN-install/master.ipa.test/):
```
DEBUG: Command: /usr/sbin/runuser -u pkiuser -- /usr/bin/env java -classpath /usr/share/tomcat/bin/tomcat-juli.jar:/usr/share/java/tomcat-servlet-api.jar:/usr/share/pki/ca/webapps/ca/WEB-INF/lib/*:/var/lib/pki/pki-tomcat/common/lib/*:/usr/share/pki/lib/* -Djavax.sql.DataSource.Factory=org.apache.commons.dbcp.BasicDataSourceFactory -Dcatalina.base=/var/lib/pki/pki-tomcat -Dcatalina.home=/usr/share/tomcat -Djava.endorsed.dirs= -Djava.io.tmpdir=/var/lib/pki/pki-tomcat/temp -Djava.util.logging.config.file=/etc/pki/pki-tomcat/logging.properties -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager -Dcom.redhat.fips=false org.dogtagpki.server.cli.PKIServerCLI ca-user-mod --add-see-also CN=CA Subsystem,O=Red Hat, Inc. --debug pkidbuser
INFO: Loading /var/lib/pki/pki-tomcat/ca/conf/CS.cfg
FINE: PlainPasswordFile: Initializing PlainPasswordFile
FINE: LdapAuthInfo: init()
FINE: LdapAuthInfo: init begins
FINE: LdapAuthInfo: init ends
FINE: TCP Keep-Alive: true
FINE: Creating LdapBoundConnFactor(UGSubsystem)
FINE: LdapBoundConnFactory: initialization
FINE: LdapAuthInfo: init()
FINE: LdapAuthInfo: init begins
FINE: LdapAuthInfo: init ends
FINE: LdapBoundConnFactory: doCloning: true
FINE: LdapBoundConnFactory: mininum: 3
FINE: LdapBoundConnFactory: maximum: 15
FINE: LdapBoundConnFactory: host: master.ipa.test
FINE: LdapBoundConnFactory: port: 389
FINE: LdapBoundConnFactory: secure: false
FINE: LdapBoundConnFactory: authentication: 1
FINE: LdapBoundConnFactory: makeConnection(false)
FINE: TCP Keep-Alive: true
FINE: LdapAuthInfo: init: prompt is internaldb
FINE: LdapAuthInfo: init: try getting from memory cache
FINE: LdapAuthInfo: init: password not in memory
FINE: LdapAuthInfo: getPasswordFromStore: try to get it from password store
FINE: LdapAuthInfo: getPasswordFromStore: about to get from passwored store: internaldb
FINE: LdapAuthInfo: getPasswordFromStore: password store available
FINE: LdapAuthInfo: getPasswordFromStore: password found for prompt in password store
FINE: LdapAuthInfo: password ok: store in memory cache
FINE: LdapBoundConnection: Connecting to master.ipa.test:389 with basic auth as cn=Directory Manager
FINE: LdapBoundConnFactory: increasing minimum connections by 3
FINE: LdapBoundConnFactory: total connections: 3
FINE: LdapBoundConnFactory: number of connections: 3
FINE: LdapBoundConnFactory: getting a connection
FINE: LdapBoundConnFactory: master connection is connected: true
FINE: LdapBoundConnFactory: connection already connected: true
FINE: LdapBoundConnFactory: number of connections: 2
FINE: LdapBoundConnFactory: number of connections: 3
FINE: Destroying LdapBoundConnFactory(UGSubsystem)
FINE: LdapBoundConnFactory: disconnecting master connection
com.netscape.certsrv.base.BadRequestException: Invalid attribute syntax.
	at com.netscape.certsrv.ldap.LDAPExceptionConverter.toPKIException(LDAPExceptionConverter.java:43)
	at com.netscape.cmscore.usrgrp.UGSubsystem.addSeeAlso(UGSubsystem.java:816)
	at org.dogtagpki.server.cli.SubsystemUserModifyCLI.execute(SubsystemUserModifyCLI.java:122)
	at org.dogtagpki.cli.CommandCLI.execute(CommandCLI.java:57)
	at org.dogtagpki.cli.CLI.execute(CLI.java:352)
	at org.dogtagpki.cli.CLI.execute(CLI.java:352)
	at org.dogtagpki.cli.CLI.execute(CLI.java:352)
	at org.dogtagpki.server.cli.PKIServerCLI.execute(PKIServerCLI.java:92)
	at org.dogtagpki.server.cli.PKIServerCLI.main(PKIServerCLI.java:122)
Caused by: netscape.ldap.LDAPException: error result (21); seeAlso: value #0 invalid per syntax
; Invalid syntax
	at netscape.ldap.LDAPConnection.checkMsg(Unknown Source)
	at netscape.ldap.LDAPConnection.modify(Unknown Source)
	at netscape.ldap.LDAPConnection.modify(Unknown Source)
	at netscape.ldap.LDAPConnection.modify(Unknown Source)
	at netscape.ldap.LDAPConnection.modify(Unknown Source)
	at com.netscape.cmscore.usrgrp.UGSubsystem.addSeeAlso(UGSubsystem.java:803)
	... 7 more
```

ipa-server-install is called with the following arguments:
`ipa-server-install -n ipa.test -r IPA.TEST -p Secret.123 -a Secret.123 --domain-level=1 -U --setup-dns --forwarder 192.168.122.1 --auto-reverse --setup-kra --subject-base 'O=Red Hat\\, Inc.' --ca-subject 'CN=IPA CA,O=Corporation 1604263946\\, Inc.'`

Installed packages: 
pki-server-10.10.0-1.20201030024828UTC.263739df.fc32.noarch

Note that the issue was already seen last week with PR #[498](https://github.com/freeipa-pr-ci2/freeipa/pull/498) and pki-server-10.10.0-0.2.beta1.20201023203338UTC.42ab987a.fc32.noarch but did not happen on PR #[483](https://github.com/freeipa-pr-ci2/freeipa/pull/483) with pki-server-10.10.0-0.1.alpha1.20201016000407UTC.d9607c2b.fc32.noarch. The regression was introduced between 20201016 and 20201023.

Companion issue on freeipa side: https://pagure.io/freeipa/issue/8562

**Comment by cipherboy** [comment] 2020-11-02 14:28
Per @rcritten: LDAP error means syntax was wrong somewhere (string to integer, **missing dn** or something similar). Might also be a change in enforcement in DS, worth checking.

@edewata could you take a look? Only happening in one specific test, but seems like a recent regression.

**Comment by edewata** [comment] 2020-11-02 20:30
Apparently there's an existing bug that got exposed due to recent changes.
It's being addressed in PR https://github.com/dogtagpki/pki/pull/3369.

**Closed** 2020-11-03 01:54 UTC
